// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VendingAPI.Data;

namespace VendingAPI.Migrations
{
    [DbContext(typeof(VendingContext))]
    [Migration("20200426090723_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VendingAPI.Models.Coin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Coins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 100,
                            Value = 10
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 100,
                            Value = 20
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 100,
                            Value = 50
                        },
                        new
                        {
                            Id = 4,
                            Quantity = 100,
                            Value = 100
                        });
                });

            modelBuilder.Entity("VendingAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(160)")
                        .HasMaxLength(160);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tea",
                            Price = 130,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 2,
                            Name = "Expresso",
                            Price = 180,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 3,
                            Name = "Juice",
                            Price = 180,
                            Quantity = 20
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chicken soup",
                            Price = 180,
                            Quantity = 15
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
